name: solidbin
channels:
  - bioconda
  - defaults
dependencies:
  - nomkl
  - biopython>=1.74
  - numpy>=1.16.4
  - pandas>=0.25.0
  - python>=3.7.1
  - scikit-learn>=0.21.2
  - scipy>=1.3.0
  - bedtools=2.28.0
  - minimap2=2.17
  - samtools=1.9

